name: trabalho_final_dpm
description: App final para disciplina - IFPI
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"  # Correção necessária para Flutter 3.38.3

dependencies:
  flutter:
    sdk: flutter
  
  flutter_dotenv: ^5.1.0

  cupertino_icons: ^1.0.8
  provider: ^6.1.2

  # Banco de dados local
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  flutter_secure_storage: ^9.2.2

  # Localização e Mapas
  geolocator: ^10.1.0
  google_maps_flutter: ^2.5.3

  uuid: ^4.3.3

  # Firebase - versões compatíveis com Flutter 3.38.3
  firebase_core: ^3.7.0
  firebase_auth: ^5.3.2

  flutter_local_notifications: ^17.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  hive_generator: ^2.0.1
  build_runner: ^2.4.11

dependency_overrides:
  js: ^0.7.0  # CORREÇÃO dos erros “PromiseJsImpl not found”

flutter:
  uses-material-design: true